server:
#  port: 8081
  port: 5000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle11g:1521:XE
    username: system
    password: oracle

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springdocker.vo


